name: Mirror Repository Workflow
on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action on
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror_job:
    name: Mirror Repository Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Mirror Repository
      uses: GHAS-Dummy/testing-github-action@v1
      with:
        target_org: Test-MirrorOrg
        access_token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
